import 'dart:io';

void main() {
  final locales = <String, Map<String, String>>{
    'tr': {
      'reward_ready': 'Günün Ödülü Hazır!',
      'reward_title': 'Günün ödülü',
      'streak_line': '{n} günlük seri — {reward}',
      'reward_tomorrow': 'Yarının ödülü: {reward}',
      'claim': 'Al',
      'free_play': 'Bugünkü Ücretsiz Oyunun',
      'ready_badge': 'HAZIR',
      'free_today': 'Reklamsız oyna — sadece bugün',
      'free_ad': 'Sonraki oyun öncesi reklam açılır',
      'quick_start': 'Hızlı Başla',
      'see_all': 'Tümü →',
      'popular': 'Popüler Kategoriler',
      'see_categories': 'Tüm Kategorileri Gör ({n})',
      'weekly': 'HAFTALIK ETKİNLİK',
      'league_started': 'Luno Ligi Başladı!',
      'league_prize': 'Bu hafta en çok puan topla, 10.000 altın kazan',
      'join': 'KATIL',
      'ad_slot': 'Reklam Alanı — Banner',
      'q_count': '{n} soru',
      'minutes': '{n} dk',
      'seconds': '{n} sn',
      'untimed': 'Süresiz',
      'subs_n': '{n} alt kategori',
      'search_category': 'Kategori ara...',
      'subcategories': 'ALT KATEGORİLER',
      'mixed_subs': 'Tüm alt kategorilerden karışık',
      'difficulty_level': 'ZORLUK SEVİYESİ',
      'diff_easy': 'Kolay',
      'diff_medium': 'Orta',
      'diff_hard': 'Zor',
      'diff_legend': 'Efsane',
      'question_count': 'SORU SAYISI',
      'mode_section': 'MOD',
      'mode_opt_hizli': 'Hızlı Tur (15 sn)',
      'mode_opt_klasik': 'Klasik Tur (20 sn)',
      'mode_opt_sakin': 'Sakin Mod (Süresiz)',
      'start_game': '🚀 Oyunu Başlat',
      'preparing': '🎮 Sorular hazırlanıyor...',
      'mode_blurb_hizli': '10 soru • 15 sn • 1.5x puan',
      'mode_blurb_klasik': '20 soru • 20 sn • 1x puan',
      'mode_blurb_maraton': '50 soru • 15 dk toplam süre',
      'mode_blurb_sakin': '10 soru • Süresiz • 0.5x puan',
      'mode_blurb_duello': 'Birebir • Kurucu seçer • Can yok',
      'mode_blurb_grup': '2-10 kişi • 15 sn',
      'mode_blurb_oda': 'Arkadaşlarınla oda kur • Can yok',
      'mode_blurb_gunluk': 'Günde 1 soru • 2x puan',
      'mode_blurb_yarisma': '20 soru • Günde 1 • Can yok',
      'mode_blurb_lig': 'Haftalık turnuva • 20 soru',
      'level': 'Seviye {n}',
      'total_games': 'Toplam Oyun',
      'correct_ratio': 'Doğru Oranı',
      'best_score': 'En Yüksek Puan',
      'login_streak': 'Giriş Serisi',
      'days': '{n} gün',
      'badges': 'ROZETLER',
      'stats': 'İstatistikler',
      'stats_sub': 'Geçmiş ve skorlar',
      'tasks': 'Görevler',
      'no_games': 'Henüz oyun yok',
      'games_n': '{n} oyun',
      'settings_sub': 'Profil ve bildirim',
      'invite': 'Davet',
      'sign_in': 'Giriş',
      'sign_in_sub': 'Hesabını bu cihazda aç',
      'no_achievements': '🎯 Henüz başarı tamamlamadın.',
      'account_info': 'Hesap Bilgileri',
      'privacy': 'Gizlilik',
      'privacy_sub': 'Gizlilik ve koşullar',
      'support': 'DESTEK',
      'help': 'Yardım & SSS',
      'how_to': 'Nasıl oynanır',
      'contact': 'İletişim',
      'about': 'Hakkında',
      'username': 'Kullanıcı adı',
      'city': 'Şehir',
      'no_events': 'Kayıtlı etkinlik yok.',
      'notify_title': 'Bildirim',
      'notify_body':
          'Günlük ödül ve lig hatırlatması için bildirim izni istenir. Tarayıcıda sistem izni açılmaz.',
      'ok': 'Tamam',
      'intro_tagline': 'Bilgiye Luno Kat!',
      'intro_sub': '60 kategori, 6 mod, binlerce soru',
      'intro_step1_title': 'Kategori Seç',
      'intro_step1_body': 'Tarih, bilim, spor, mitoloji... 60 farklı kategoriden istediğini seç',
      'intro_step2_title': 'Soruları Cevapla',
      'intro_step2_body': 'Süreli veya süresiz modda bilgini test et, jokerlerini akıllı kullan',
      'intro_step3_title': 'Ödülleri Kazan',
      'intro_step3_body': 'Altın, rozet, unvan kazan. Liderlik tablosunda zirveye çık',
      'intro_start': '🚀 Hemen Başla',
      'play_again_btn': '🔄 Tekrar Oyna',
      'retry': '🔄 Tekrar Dene',
      'gold': 'altın',
      'diamond': 'elmas',
      'joker': 'joker',
      'copied': 'Sonuç panoya kopyalandı.',
      'start': 'Başla',
      'event': 'Etkinlik',
    },
    'en': {
      'reward_ready': 'Daily reward ready!',
      'reward_title': 'Daily reward',
      'streak_line': '{n}-day streak — {reward}',
      'reward_tomorrow': "Tomorrow's reward: {reward}",
      'claim': 'Claim',
      'free_play': 'Your free game today',
      'ready_badge': 'READY',
      'free_today': 'Play without ads — today only',
      'free_ad': 'An ad plays before the next game',
      'quick_start': 'Quick start',
      'see_all': 'All →',
      'popular': 'Popular categories',
      'see_categories': 'See all categories ({n})',
      'weekly': 'WEEKLY EVENT',
      'league_started': 'Luno League is on!',
      'league_prize': 'Score the most this week and win 10,000 gold',
      'join': 'Join',
      'ad_slot': 'Ad slot — Banner',
      'q_count': '{n} questions',
      'minutes': '{n} min',
      'seconds': '{n} sec',
      'untimed': 'Untimed',
      'subs_n': '{n} subcategories',
      'search_category': 'Search categories...',
      'subcategories': 'SUBCATEGORIES',
      'mixed_subs': 'Mixed from all subcategories',
      'difficulty_level': 'DIFFICULTY',
      'diff_easy': 'Easy',
      'diff_medium': 'Medium',
      'diff_hard': 'Hard',
      'diff_legend': 'Legend',
      'question_count': 'QUESTION COUNT',
      'mode_section': 'MODE',
      'mode_opt_hizli': 'Quick round (15 sec)',
      'mode_opt_klasik': 'Classic round (20 sec)',
      'mode_opt_sakin': 'Calm mode (Untimed)',
      'start_game': '🚀 Start game',
      'preparing': '🎮 Preparing questions...',
      'mode_blurb_hizli': '10 questions • 15 sec • 1.5x score',
      'mode_blurb_klasik': '20 questions • 20 sec • 1x score',
      'mode_blurb_maraton': '50 questions • 15 min total',
      'mode_blurb_sakin': '10 questions • Untimed • 0.5x score',
      'mode_blurb_duello': '1v1 • Host picks the setup • No life',
      'mode_blurb_grup': '2–10 players • 15 sec',
      'mode_blurb_oda': 'Create a room with friends • No life',
      'mode_blurb_gunluk': '1 question a day • 2x score',
      'mode_blurb_yarisma': '20 questions • Once a day • No life',
      'mode_blurb_lig': 'Weekly tournament • 20 questions',
      'level': 'Level {n}',
      'total_games': 'Games played',
      'correct_ratio': 'Accuracy',
      'best_score': 'Best score',
      'login_streak': 'Login streak',
      'days': '{n} days',
      'badges': 'BADGES',
      'stats': 'Statistics',
      'stats_sub': 'History and scores',
      'tasks': 'Quests',
      'no_games': 'No games yet',
      'games_n': '{n} games',
      'settings_sub': 'Profile and notifications',
      'invite': 'Invite',
      'sign_in': 'Sign in',
      'sign_in_sub': 'Open your account on this device',
      'no_achievements': '🎯 No achievements yet.',
      'account_info': 'Account details',
      'privacy': 'Privacy',
      'privacy_sub': 'Privacy and terms',
      'support': 'SUPPORT',
      'help': 'Help & FAQ',
      'how_to': 'How to play',
      'contact': 'Contact',
      'about': 'About',
      'username': 'Username',
      'city': 'City',
      'no_events': 'No saved events.',
      'notify_title': 'Notifications',
      'notify_body':
          'We ask for notification permission for daily rewards and league reminders. Browsers do not open the system prompt.',
      'ok': 'OK',
      'intro_tagline': 'Add Luno to your knowledge!',
      'intro_sub': '60 categories, 6 modes, thousands of questions',
      'intro_step1_title': 'Pick a category',
      'intro_step1_body': 'History, science, sports, mythology… choose from 60 categories',
      'intro_step2_title': 'Answer questions',
      'intro_step2_body': 'Test yourself timed or untimed and use jokers wisely',
      'intro_step3_title': 'Earn rewards',
      'intro_step3_body': 'Win gold, badges, and titles. Climb the leaderboard',
      'intro_start': '🚀 Start now',
      'play_again_btn': '🔄 Play again',
      'retry': '🔄 Try again',
      'gold': 'gold',
      'diamond': 'diamonds',
      'joker': 'jokers',
      'copied': 'Result copied to clipboard.',
      'start': 'Start',
      'event': 'Event',
    },
  };

  // Other 8 languages fall back through English then Turkish at runtime if missing,
  // but we fill them from English so none fall through to Turkish chrome.
  for (final id in const ['de', 'es', 'fr', 'it', 'ru', 'nl', 'pt', 'pl']) {
    locales[id] = Map<String, String>.from(locales['en']!);
  }
  // Keep a few native-looking tokens for the common chrome words.
  locales['de']!.addAll({
    'claim': 'Holen',
    'join': 'Mitmachen',
    'start': 'Start',
    'ok': 'OK',
    'diff_easy': 'Leicht',
    'diff_medium': 'Mittel',
    'diff_hard': 'Schwer',
    'diff_legend': 'Legende',
    'gold': 'Gold',
    'diamond': 'Diamanten',
    'joker': 'Joker',
    'language_keep': '',
  });
  locales['de']!.remove('language_keep');
  locales['es']!.addAll({
    'claim': 'Recoger',
    'join': 'Unirse',
    'start': 'Empezar',
    'diff_easy': 'Fácil',
    'diff_medium': 'Media',
    'diff_hard': 'Difícil',
    'diff_legend': 'Leyenda',
    'gold': 'oro',
    'diamond': 'diamantes',
    'joker': 'comodines',
  });
  locales['fr']!.addAll({
    'claim': 'Prendre',
    'join': 'Rejoindre',
    'start': 'Commencer',
    'diff_easy': 'Facile',
    'diff_medium': 'Moyen',
    'diff_hard': 'Difficile',
    'diff_legend': 'Légende',
    'gold': 'or',
    'diamond': 'diamants',
    'joker': 'jokers',
  });
  locales['it']!.addAll({
    'claim': 'Prendi',
    'join': 'Partecipa',
    'start': 'Inizia',
    'diff_easy': 'Facile',
    'diff_medium': 'Media',
    'diff_hard': 'Difficile',
    'diff_legend': 'Leggenda',
    'gold': 'oro',
    'diamond': 'diamanti',
    'joker': 'jolly',
  });
  locales['ru']!.addAll({
    'claim': 'Забрать',
    'join': 'Участвовать',
    'start': 'Старт',
    'diff_easy': 'Лёгкий',
    'diff_medium': 'Средний',
    'diff_hard': 'Сложный',
    'diff_legend': 'Легенда',
    'gold': 'золота',
    'diamond': 'алмазов',
    'joker': 'джокеров',
  });
  locales['nl']!.addAll({
    'claim': 'Pakken',
    'join': 'Meedoen',
    'start': 'Start',
    'diff_easy': 'Makkelijk',
    'diff_medium': 'Gemiddeld',
    'diff_hard': 'Moeilijk',
    'diff_legend': 'Legende',
    'gold': 'goud',
    'diamond': 'diamanten',
    'joker': 'jokers',
  });
  locales['pt']!.addAll({
    'claim': 'Receber',
    'join': 'Participar',
    'start': 'Começar',
    'diff_easy': 'Fácil',
    'diff_medium': 'Média',
    'diff_hard': 'Difícil',
    'diff_legend': 'Lenda',
    'gold': 'ouro',
    'diamond': 'diamantes',
    'joker': 'curingas',
  });
  locales['pl']!.addAll({
    'claim': 'Odbierz',
    'join': 'Dołącz',
    'start': 'Start',
    'diff_easy': 'Łatwy',
    'diff_medium': 'Średni',
    'diff_hard': 'Trudny',
    'diff_legend': 'Legenda',
    'gold': 'złota',
    'diamond': 'diamentów',
    'joker': 'jokerów',
  });

  final buf = StringBuffer()
    ..writeln('/// Extra UI chrome for Luno Bilgi. Keys must match screen / controller usage.')
    ..writeln('const bilgiChrome = <String, Map<String, String>>{');
  for (final entry in locales.entries) {
    buf.writeln("  '${entry.key}': {");
    for (final row in entry.value.entries) {
      buf.writeln("    '${row.key}': ${_dartString(row.value)},");
    }
    buf.writeln('  },');
  }
  buf.writeln('};');
  File('lib/games/luno_bilgi/bilgi_l10n_chrome.dart').writeAsStringSync(buf.toString());
  stdout.writeln('wrote ${locales.length} locales, ${locales['en']!.length} keys');
}

String _dartString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\$', r'\$');
  return "'$escaped'";
}
