String fallText(String locale, String key) {
  final table = locale == 'en' ? _en : _tr;
  return table[key] ?? _tr[key] ?? key;
}

const _tr = {
  'play': 'Oyna',
  'league': 'Lig',
  'shop': 'Mağaza',
  'profile': 'Profil',
  'slogan': 'Harfler düşer, kelimeler doğar.',
  'pick': 'Zorluk seç',
  'easy': 'Kolay',
  'normal': 'Normal',
  'hard': 'Zor',
  'legend': 'Efsane',
  'coins': 'Coin',
  'ad_coin': 'Reklam izle +5',
  'ad_coin_done': 'Bugünkü reklam hakkı doldu',
  'banner': 'Oyun dışı banner · gece kapanır',
  'no_midgame_ad': 'Oyun içinde reklam yok',
  'watch': 'Reklam izle, hemen oyna',
  'wait': 'Bekle',
  'menu': 'Menü',
  'premium': 'Premium: bekleme yok',
  'result': 'Koşu bitti',
  'words': 'Kelime',
  'combo': 'Kombo',
  'score': 'Skor',
  'pause': 'Duraklat',
  'resume': 'Devam',
  'lives': 'Can',
  'mock_ad': 'Ödüllü reklam',
  'skip_wait': 'Beklemeyi geç',
};

const _en = {
  'play': 'Play',
  'league': 'League',
  'shop': 'Shop',
  'profile': 'Profile',
  'slogan': 'Letters fall, words are born.',
  'pick': 'Choose difficulty',
  'easy': 'Easy',
  'normal': 'Normal',
  'hard': 'Hard',
  'legend': 'Legend',
  'coins': 'Coins',
  'ad_coin': 'Watch ad +5',
  'ad_coin_done': 'Daily ad reward used up',
  'banner': 'Home banner · hidden at night',
  'no_midgame_ad': 'No ads during a run',
  'watch': 'Watch ad, play now',
  'wait': 'Wait',
  'menu': 'Menu',
  'premium': 'Premium: no wait',
  'result': 'Run over',
  'words': 'Words',
  'combo': 'Combo',
  'score': 'Score',
  'pause': 'Pause',
  'resume': 'Resume',
  'lives': 'Lives',
  'mock_ad': 'Rewarded ad',
  'skip_wait': 'Skip the wait',
};
